version: '3'
services:
  mogo:
    image: mongo:latest
    container_name: mongo_instance
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

app:
  build:
    context:
    dockerfile: dockerfile
    args:
    - PORT=${PORT}
  restart: always
  container_name: cpen321_app
  environment:
    - DB_URI=${DB_URI}
    - PORT=${PORT}
  ports:
  - "${PORT}:${PORT}"
  depends on:configs:
  - mongo
  command: npm start

volumes:
  mono_data: